<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Return to shop</name>
   <tag></tag>
   <elementGuidId>f162fa38-0c05-4544-b28b-36a7ed51a0d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[3]/div/div[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5b7dcea2-df90-4721-a4a0-aba6af3364e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-5 font-noto transition transition-colors-opacity text-black border border-black bg-grey hover:bg-gray-100 py-2.75 text-base rounded-full self-start w-full mb-4 font-bold text-center bg-white sm:mb-10 1.5xl:mb-6 1.5xl:self-end md:text-base whitespace-nowrap sm:w-auto 1.5xl:hidden</value>
      <webElementGuid>7da935cc-793e-478f-9d46-37256cab6855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>cartPage.returnToShop</value>
      <webElementGuid>e84ad616-f2d0-4639-a77e-599e03af2edf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/stock-photo/</value>
      <webElementGuid>1251671e-82d9-48a9-9919-f125c8b1c927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>cartPage.returnToShop</value>
      <webElementGuid>819629e6-8b1f-429a-a4fc-803d6aed6d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Return to shop</value>
      <webElementGuid>9e805889-a6cd-4deb-9aec-3132a9803587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;flex flex-col justify-between min-h-full&quot;]/div[@class=&quot;pb-48 bg-white 1.5xl:flex 1.5xl:flex-row 1.5xl:justify-center font-noto&quot;]/div[@class=&quot;min-w-full px-4 pt-10 pb-0 max-w-7xl 1.5xl:min-w-12 grid grid-cols-1 1.5xl:grid-cols-12 min-h-screen-50 1.5xl:justify-center 1.5xl:flex-row gap-x-0 1.5xl:gap-x-12 content-wrap 1.5xl:pt-14&quot;]/div[@class=&quot;1.5xl:relative col-span-5&quot;]/div[@class=&quot;flex flex-col items-end w-full 1.5xl:sticky 1.5xl:top-14 1.5xl:w-auto&quot;]/a[@class=&quot;px-5 font-noto transition transition-colors-opacity text-black border border-black bg-grey hover:bg-gray-100 py-2.75 text-base rounded-full self-start w-full mb-4 font-bold text-center bg-white sm:mb-10 1.5xl:mb-6 1.5xl:self-end md:text-base whitespace-nowrap sm:w-auto 1.5xl:hidden&quot;]</value>
      <webElementGuid>c6b58d9a-6199-456e-862a-53c1d96a66b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[3]/div/div[2]/div/a</value>
      <webElementGuid>4c4f2a1b-0a7b-4cab-8327-1d737e2a8335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Return to shop')])[2]</value>
      <webElementGuid>c8c71ba5-7b02-4ad9-b84d-e39d211f10e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/stock-photo/')])[2]</value>
      <webElementGuid>1badd9a9-4d5b-444b-b823-c30d963e9655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>05cbfc56-9a01-4d0d-8f5a-0d3a725a6e2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/stock-photo/' and (text() = 'Return to shop' or . = 'Return to shop')]</value>
      <webElementGuid>4331aa1b-d197-41bb-956a-9df0c6e7c592</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
