<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_absolute top-0 left-0 h-full bg-black opa_a5a117</name>
   <tag></tag>
   <elementGuidId>89641354-f1d7-4c2a-82a3-d8115854ac08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[5]/div/div[3]/div/div/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a7a85ac3-01f6-46c5-8ff7-9252b184d031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute top-0 left-0 h-full bg-black opacity-0 group-hover:opacity-100 bg-opacity-20 duration-200 z-2</value>
      <webElementGuid>1e21a4cc-09b0-447e-aac0-0862aa4b4fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>2001 Smart car mk1 Stock Photo</value>
      <webElementGuid>74ba9008-3651-4a0f-b147-c6d2df21498f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/stock-photo-2001-smart-car-mk1-27168642.html?imageid=5DDE41CF-5FF8-4E73-AB7E-C45BFBC69884&amp;p=1480&amp;pn=1&amp;searchId=606da529b6a35ab16f200c4485d270ec&amp;searchtype=0</value>
      <webElementGuid>95ad4a37-266b-4d19-b2f2-c190ef9e6ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;flex flex-col justify-between min-h-full&quot;]/div[@class=&quot;flex w-full h-full&quot;]/div[@class=&quot;w-full min-h-screen&quot;]/div[@class=&quot;w-full image-gallery&quot;]/div[@class=&quot;px-5 mt-4&quot;]/div[@class=&quot;border-0 border-b md:border-b-0 border-grey-mid py-5 md:py-3&quot;]/div[1]/div[@class=&quot;relative w-auto&quot;]/div[@class=&quot;absolute group&quot;]/a[@class=&quot;absolute top-0 left-0 h-full bg-black opacity-0 group-hover:opacity-100 bg-opacity-20 duration-200 z-2&quot;]</value>
      <webElementGuid>cb7c7466-6c42-41e8-82bd-6f40fef94607</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[5]/div/div[3]/div/div/div/div/div/a</value>
      <webElementGuid>3be39148-91dd-40b6-a798-27edfae6bb33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/stock-photo-2001-smart-car-mk1-27168642.html?imageid=5DDE41CF-5FF8-4E73-AB7E-C45BFBC69884&amp;p=1480&amp;pn=1&amp;searchId=606da529b6a35ab16f200c4485d270ec&amp;searchtype=0')]</value>
      <webElementGuid>c830a9e5-84c5-405f-a0fe-c688c584c797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/a</value>
      <webElementGuid>5eeef48c-6f95-43e6-9283-77ad17c6c032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = '2001 Smart car mk1 Stock Photo' and @href = '/stock-photo-2001-smart-car-mk1-27168642.html?imageid=5DDE41CF-5FF8-4E73-AB7E-C45BFBC69884&amp;p=1480&amp;pn=1&amp;searchId=606da529b6a35ab16f200c4485d270ec&amp;searchtype=0']</value>
      <webElementGuid>53e461e7-0a93-443d-bc2b-474e3d56619f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
