<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Email addressPlease enter a valid emai_cac755</name>
   <tag></tag>
   <elementGuidId>04600975-4a1b-4014-bb24-2a3e2fb9f448</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signInPwdForm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='signInPwdForm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>69a24149-380d-4cd3-b2f4-97ae6c85e7ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signInPwdForm</value>
      <webElementGuid>442865d8-508f-4e28-83c8-7e252d0a6696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full font-noto w-full</value>
      <webElementGuid>54045612-e14e-4c48-999d-60c6a3c930a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email addressPlease enter a valid email addressPasswordShowForgot your password?Sign inNot a member?Create a free account</value>
      <webElementGuid>a25de0da-0699-48c0-86d6-dbcd7599c25e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signInPwdForm&quot;)</value>
      <webElementGuid>3e2d7c8b-87c7-4cbe-8356-a1176d5e06a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@id='signInPwdForm']</value>
      <webElementGuid>d6d53e78-2952-44b8-8a2b-5fd7e99bd9b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/form</value>
      <webElementGuid>bc28229c-acd6-496f-8def-922e8059812d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>3ee41544-b00e-4678-8194-70a958c363dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[@id = 'signInPwdForm' and (text() = 'Email addressPlease enter a valid email addressPasswordShowForgot your password?Sign inNot a member?Create a free account' or . = 'Email addressPlease enter a valid email addressPasswordShowForgot your password?Sign inNot a member?Create a free account')]</value>
      <webElementGuid>1a1adc85-e79c-4ea7-b0b3-6ac739835a2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
