<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Video</name>
   <tag></tag>
   <elementGuidId>6f6727c6-aa9b-4fb2-9202-f017eb42f7f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='search']/div/div/div/ul/li[7]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>155cb767-96c1-4d90-ad78-f0b050e362ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a017be3c-d174-4fbd-a493-44a9adeb8bb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center px-4 py-2.5 text-sm text-grey-black hover:bg-gray-100</value>
      <webElementGuid>943ae90f-c782-497f-b68f-18c7149a9ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Video</value>
      <webElementGuid>8c121fba-65d2-46b0-93bf-89be0d4f6d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search&quot;)/div[1]/div[@class=&quot;search-class flex flex-row items-center border-black-border rounded-full border border-black h-12 2xs:p-0 md:p-0 bg-white md:my-2 3xs:h-11 2sm:h-10 sm:h-11 xl:h-12 3xs:rounded-none 2sm:rounded-full 2sm:min-w-80 lg:min-w-30&quot;]/div[@class=&quot;relative flex flex-row items-center flex-1 bg-transparent border-0 cursor-pointer text-grey-black md:mx-0 h-13 noto-sans md:rounded-tl-full md:rounded-bl-full&quot;]/ul[@class=&quot;absolute left-0 z-50 bg-white shadow-md top-full w-auto mt-1 border-b border-black md:border-0 md:mt-2 md:rounded&quot;]/li[7]/div[@class=&quot;flex items-center px-4 py-2.5 text-sm text-grey-black hover:bg-gray-100&quot;]</value>
      <webElementGuid>23263e05-6d1c-4b7d-a608-eb1e1d8e5415</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search']/div/div/div/ul/li[7]/div</value>
      <webElementGuid>dfee5983-d64c-479d-bb5f-c99212f8d220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/div</value>
      <webElementGuid>a721ad85-b557-47c4-af5f-6b2ae6ef3d60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Video' or . = 'Video')]</value>
      <webElementGuid>e2ead205-e00a-4fdc-9b10-2cd1adfd7695</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
