<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Search for images</name>
   <tag></tag>
   <elementGuidId>bc27a824-0dbc-4e18-920b-86e2035c055b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='search']/div/div/div/div/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>564bef9d-eef0-4b13-b938-4fa95cfa9341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>2xl:hidden text-2xs 1xs:text-base 2sm:font-noto</value>
      <webElementGuid>707a0ad9-7cfd-45c9-b662-731893d16dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search for images</value>
      <webElementGuid>efb86767-cee4-41a8-a3c4-b5ee1b841536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search&quot;)/div[1]/div[@class=&quot;search-class flex flex-row items-center border-black-border rounded-full border border-black h-12 2xs:p-0 md:p-0 bg-white md:my-2 3xs:h-11 2sm:h-10 sm:h-11 xl:h-12 3xs:rounded-none 2sm:rounded-full 2sm:min-w-80 lg:min-w-30&quot;]/div[@class=&quot;relative flex flex-row items-center flex-1 bg-transparent border-0 cursor-pointer text-grey-black md:mx-0 h-13 noto-sans md:rounded-tl-full md:rounded-bl-full&quot;]/div[@class=&quot;relative flex flex-auto h-10 border-black h-8 border-l ml-3 2sm:h-9 sm:h-10 3xs:ml-0 xl:ml-3&quot;]/label[@class=&quot;absolute w-full h-full py-2 pl-4 align-middle text-mid-grey cursor-text md:pr-4 font-noto 3xs:py-1.5&quot;]/span[@class=&quot;2xl:hidden text-2xs 1xs:text-base 2sm:font-noto&quot;]</value>
      <webElementGuid>50f7174b-5710-4e30-887f-20135a0b0500</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search']/div/div/div/div/label/span</value>
      <webElementGuid>54cd1fb8-fd51-44a6-9953-3600c85224b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>5d75c4e0-4192-47ab-ae71-5f93d5e08dbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Search for images' or . = 'Search for images')]</value>
      <webElementGuid>a409e46d-9d2d-4031-a04d-e4964f45536d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
