<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_svg-inline--fa fa-cart-shopping self-ce_f68093</name>
   <tag></tag>
   <elementGuidId>0126c2af-15f3-4932-8458-0f1c4487b627</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;header&quot;)/div[@class=&quot;flex items-center h-full whitespace-nowrap&quot;]/ul[@class=&quot;flex items-center h-full&quot;]/li[@class=&quot;md-4:ml-4 w-max hover:text-guppie text-white relative inline-flex cursor-pointer&quot;]/a[@class=&quot;text-sm flex justify-between font-bold font-bold&quot;]/span[@class=&quot;relative&quot;]/svg[@class=&quot;svg-inline--fa fa-cart-shopping self-center w-auto h-5 mr-2 text-xl md-4:text-base&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>6e643416-2413-46fb-b23d-0e689039ef08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ae2169f0-accc-466d-ac47-85b56563d819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>eea4b221-c8ff-4f30-840b-fddc954fe73e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-prefix</name>
      <type>Main</type>
      <value>far</value>
      <webElementGuid>94a9e8be-ca66-4b0d-ba33-f45eb75523b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>cart-shopping</value>
      <webElementGuid>f28f2e05-2820-4032-a86f-dc557ac67b23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svg-inline--fa fa-cart-shopping self-center w-auto h-5 mr-2 text-xl md-4:text-base</value>
      <webElementGuid>74c98588-62ae-4986-b231-6567b8ff1503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bc8e3c4a-96ba-4491-9d07-0d056a8445fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>9868a146-dba2-43ea-b94c-288eb2a3ea15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 576 512</value>
      <webElementGuid>ea70ece6-efc8-4165-8584-83cbd02adc5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;flex items-center h-full whitespace-nowrap&quot;]/ul[@class=&quot;flex items-center h-full&quot;]/li[@class=&quot;md-4:ml-4 w-max hover:text-guppie text-white relative inline-flex cursor-pointer&quot;]/a[@class=&quot;text-sm flex justify-between font-bold font-bold&quot;]/span[@class=&quot;relative&quot;]/svg[@class=&quot;svg-inline--fa fa-cart-shopping self-center w-auto h-5 mr-2 text-xl md-4:text-base&quot;]</value>
      <webElementGuid>ff381573-8590-4573-a8a2-367ea0f5252b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
